import json,html
from pathlib import Path
root=Path(__file__).parent
P=json.loads((root/'source-copy.json').read_text())
def esc(t):return html.escape(t)
def at(t):return P.index(t)
def paras(a,b):return ''.join('<p>'+esc(t)+'</p>' for t in P[at(a):at(b)] if not t.startswith('['))
def tag(t):return '<p>'+esc(t)+'</p>'
def heading(k,t):return '<p class="eyebrow">'+k+'</p><h2>'+t+'</h2>'
S=[]
S.append('''<section class="dark-section" id="approach"><div class="wrap tension"><div><p class="eyebrow">THE REAL CHALLENGE</p><div class="seconds">30<span>seconds.</span></div><h2>AI can create a<br>learning program.</h2><p class="muted-light">Objectives. Agenda. Exercises. Case studies.<br>Reflection questions. Assessments.</p></div><div class="tension-copy"><h2>And it can still be<br><em>bad learning design.</em></h2>'''+paras('AI is astonishingly good at creating something that looks complete.','This is not a prompt-engineering workshop.')+'</div></div></section>')
S.append('<section class="wrap section approach">'+heading('01 / THE APPROACH','Learning design first.<br><span class="serif">AI as an accelerator.</span>')+'<div class="approach-intro">'+paras('This is not a prompt-engineering workshop.','At every stage of the design process, we will ask six questions:')+'</div><p class="question-intro">At every stage of the design process, we will ask six questions:</p><div class="questions-grid">')
for i,t in enumerate(P[at('What can AI do well here?'):at('How do we know the final design is actually good?')+1]):S.append(f'<div class="question"><span>0{i+1}</span><h3>{esc(t)}</h3></div>')
S.append('</div><a class="text-link" href="#join">Reserve my place ↗</a></section>')
S.append('<section class="yellow-section"><div class="wrap section journey">'+heading('02 / YOUR WORK, TRANSFORMED','Bring one.<br><span class="serif">Leave with one.</span>')+'<div><p class="lead">You will not practise on imaginary examples.</p><h3>Bring one real piece of work.</h3>'+tag(P[at('It could be a workshop you already deliver, a new program you need to design, a corporate academy, a learning module, a client brief, or a course that is not working as well as you want.')])+'<h3>Leave with a redesigned program.</h3>'+paras('Throughout the day, you will apply the methodology, prompts and quality criteria directly to your own work.','[Graphic designer: This section can be treated as a simple visual journey: BRING → WORK → REDESIGN → LEAVE WITH SOMETHING REAL.]')+'</div><ol class="journey-line"><li>Bring</li><li>Work</li><li>Redesign</li><li>Leave with<br>something real.</li></ol></div></section>')
S.append('<section class="wrap section" id="outcomes">'+heading('03 / THE TAKEAWAYS','The day ends.<br><span class="serif">The work stays with you.</span>')+'<p>By the end of the day, you should leave with:</p><div class="outcomes">')
a=at('01  Your own redesigned learning program')
for i in range(6):
 title=P[a+i*2][4:];desc=P[a+i*2+1];S.append(f'<article><span class="number">0{i+1}</span><div><h3>{esc(title)}</h3><p>{esc(desc)}</p></div></article>')
S.append('</div></section>')
S.append('<section class="method-section"><div class="wrap section">'+heading('04 / THE BACKBONE','AI changes the speed of design.<br><span class="serif">It does not change how humans learn.</span>')+tag(P[at('For approximately the first 90 minutes, we will refresh the T4HPL principles behind how people naturally learn.')])+'<ol class="method"><li><span>01</span>Engage</li><li><span>02</span>Learn</li><li><span>03</span>Practice</li><li><span>04</span>Perform</li></ol><div class="method-bottom"><p>Then we will work through the methodology again — this time asking, at every stage:<br><strong>What can AI help us do better or faster?</strong><br>and<br><strong>What still depends on an excellent learning designer?</strong></p>'+tag(P[at('If you already know T4HPL, this is a high-speed recalibration. If you are new to the methodology, the refresh will give you the foundations you need for the rest of the day.')])+'</div></div></section>')
S.append('''<section class="wrap section studio">'''+heading('05 / IN THE ROOM','Expect a design studio,<br><span class="serif">not a conference.</span>')+'''<div class="studio-layout"><img src="assets/discussion.png" alt="Workshop participants discussing their work together" loading="lazy"><div class="studio-words"><p>Short inputs.</p><p>Real design work.</p><p>AI experimentation.</p><p>Peer critique.</p><p>My feedback.</p><p>Redesign.</p><p class="repeat">Repeat.</p></div><img src="assets/design-table.png" alt="Hands arranging learning design materials on a workshop table" loading="lazy"></div></section>''')
S.append('<section class="wrap section day" id="day"><div class="day-heading">'+heading('06 / THE DAY','One day.<br><span class="serif">Seven purposeful parts.</span>')+'<p>09:00–17:30 · Bucharest</p><a class="button" href="#join">Reserve my place <span aria-hidden="true">↗</span></a></div><ol class="agenda">')
a=at('Part 1 — Recalibrate')
for i in range(7):S.append(f'<li><span>0{i+1}</span><div><h3>{esc(P[a+2*i].split(" — ")[1])}</h3><p>{esc(P[a+2*i+1])}</p></div></li>')
S.append('</ol></section>')
S.append('<section class="return-section"><div class="wrap section split">'+heading('07 / A FAMILIAR FOUNDATION. NEW POSSIBILITIES.','You may already know T4HPL.<br><span class="serif">This is what comes next.</span>')+'<div>'+paras('For many participants, this workshop is a return to a methodology they already use — now updated for a world in which AI can generate learning content almost instantly.','[Add 2–4 short testimonials here. Prioritise testimonials about how T4HPL changed the way people design, think about learning, or build programs — not generic praise about the facilitator.]')+'</div></div></section>')
S.append('<section class="wrap section audience">'+heading('08 / IS THIS YOUR KIND OF DAY?','This day is for you<br><span class="serif">if you design learning.</span>')+'<ul class="audience-list">')
for t in P[at('Trainers'):at('You do not need previous T4HPL experience.')]:S.append('<li>'+esc(t)+'</li>')
S.append('</ul><div class="audience-note">'+paras('You do not need previous T4HPL experience.','I have spent 20 years asking one question: what actually makes people learn?')+'</div></section>')
S.append('<section class="about dark-section" id="olimpia"><div class="wrap section"><p class="eyebrow">09 / YOUR FACILITATOR</p><div class="about-grid"><div><div class="twenty">20<span>years of asking</span></div><h2>What actually<br>makes people<br><em>learn?</em></h2><p class="signature">Olimpia Mesa</p></div><div>'+paras('I’m Olimpia Mesa, learning designer and author of Cum învață oamenii.','Join us in November')+'</div></div></div></section>')
S.append('''<section class="wrap section join" id="join">'''+heading('10 / NOVEMBER 2026 · BUCHAREST','Bring your work.<br><span class="serif">Make room for possibility.</span>')+'''<p class="lead">From AI prompts to learning programs</p><p>One day · 09:00–17:30 · In person · Limited group</p><div class="prices"><article class="early"><p class="eyebrow">EARLY BIRD</p><p class="price">€375<span>+ VAT</span></p><p>Limited early-bird places</p></article><article><p class="eyebrow">STANDARD</p><p class="price">€450<span>+ VAT</span></p><p>Standard registration</p></article><article><p class="eyebrow">LATE REGISTRATION</p><p class="price">€500–525<span>+ VAT</span></p><p>Final places</p></article></div><div class="registration-note"><h3>Registration details coming soon.</h3><p>The exact date, venue and booking link will be announced here.</p></div><p class="team-note">Bringing 3+ colleagues? A special team rate is available.<br>Company invoices can be issued.</p></section>''')
S.append('<section class="wrap section faq" id="faq"><div>'+heading('11 / GOOD QUESTIONS','Before you<br><span class="serif">bring your work.</span>')+'</div><div class="faq-list">')
a=at('Questions you may have')+1;b=at('AI can generate more learning content than we could ever use.')
for i in range(a,b,2):S.append('<details><summary>'+esc(P[i])+'<span aria-hidden="true">+</span></summary><div>'+tag(P[i+1])+'</div></details>')
S.append('</div></section>')
S.append('''<section class="closing yellow-section"><div class="wrap section"><p class="eyebrow">MORE POSSIBILITY. THE SAME PROFESSIONAL JUDGMENT.</p><p class="lead">AI can generate more learning content than we could ever use.</p><h2>The competitive advantage<br>will be knowing what<br><span class="serif">deserves to be designed.</span></h2><p class="lead">Bring one real piece of work.<br><strong>Leave with a redesigned program.</strong></p><a class="button black" href="#join">Reserve my place <span aria-hidden="true">↗</span></a><p class="micro">November 2026 · Bucharest</p></div></section>''')
f=root/'dist/index.html';s=f.read_text();s=s.replace('<div id="content"></div>',''.join(S));f.write_text(s)
